### PR TITLE
[BACKLOG-5877] Adding missing dependencies for thin driver

### PR DESCRIPTION
**Pull request by bmorrise**
http://jira.pentaho.com/browse/BACKLOG-5877

[Build Status](https://travis-ci.org/bmorrise/pdi-dataservice-plugin)

### CODE REVIEW

**Comment by bmorrise** [comment]
@mkambol While using the driver with SQuirreL I discovered that these two jars are now required. There is a longer term fix that would help us remove some of the dependencies, but will require moving logic down to the server.

**Comment by lucboudreau** [comment]
Please make sure to update all user guides and documentation following this change.

**Comment by mkambol** [comment]
@lucboudreau, I'll make sure doc has a chance to review.  Looks like the docs only point to the zip file that contains these jars, it doesn't enumerate them, so hopefully no update needed.

**Comment by bmorrise** [comment]
@mkambol I talked with Chantel and you are correct, there is no doc update here.

**Pull request merged**
