### PR TITLE
[BACKLOG-5502]ThinPreparedStatement is safe

### PR DESCRIPTION
**Pull request by hudak**
Per JDBC specification, PreparedStatement.getMetaData() should return null if not available, not throw an exception.

### CODE REVIEW

**Comment by hudak** [comment]
http://10.100.11.222:8080/job/wingman-mvn/54/console

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. mvn -DrunITs=true -f pdi-dataservice-client/pom.xml clean install && mvn -f pdi-dataservice-client/pom.xml site

Cleanup:
-------
mvn build-helper:remove-project-artifact

Changed files:
==============
  pdi-dataservice-client/src/main/java/org/pentaho/di/trans/dataservice/jdbc/ThinPreparedStatement.java
  pdi-dataservice-client/src/main/java/org/pentaho/di/trans/dataservice/jdbc/ThinStatement.java
  pdi-dataservice-client/src/test/java/org/pentaho/di/trans/dataservice/jdbc/ThinPreparedStatementTest.java










Unit test coverage change:
============
org.pentaho.di.trans.dataservice.jdbc.ThinPreparedStatement:
 * instructionPercentCoverageChange : +0.31%
 * branchPercentCoverageChange : +1.32%
 * linePercentCoverageChange : +0.33%
 * complexityPercentCoverageChange : +0.51%
 * methodPercentCoverageChange : +0.17%
    
org.pentaho.di.trans.dataservice.jdbc.ThinStatement:
 * instructionPercentCoverageChange : +0.14%
 * linePercentCoverageChange : +0.13%
    
org.pentaho.di.trans.dataservice.jdbc.ThinResultFactory:
 * branchPercentCoverageChange :**-50.00%**
 * complexityPercentCoverageChange :**-25.00%**
    
Integration test coverage change:
============
org.pentaho.di.trans.dataservice.jdbc.ThinPreparedStatement:
 * instructionPercentCoverageChange : +0.31%
 * branchPercentCoverageChange : +1.32%
 * linePercentCoverageChange : +0.33%
 * complexityPercentCoverageChange : +0.51%
 * methodPercentCoverageChange : +0.17%
    
org.pentaho.di.trans.dataservice.jdbc.ThinStatement:
 * instructionPercentCoverageChange : +0.14%
 * linePercentCoverageChange : +0.13%
    
org.pentaho.di.trans.dataservice.jdbc.ThinResultFactory:
 * branchPercentCoverageChange :**-50.00%**
 * complexityPercentCoverageChange :**-25.00%**

**Comment by hudak** [comment]
@bmorrise Reviewing pentaho/pentaho-commons-database#86
Failed to create a new data source from a data service, looks like I broke the behavior of ThinPreparedStatements when testing. This should fix it

**Comment by hudak** [comment]
[Build Status](https://travis-ci.org/hudak/pdi-dataservice-plugin)

**Comment by lucboudreau** [comment]
# Build Commands:

## Build:
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. mvn -DrunITs=true -f pdi-dataservice-client/pom.xml clean install && mvn -f pdi-dataservice-client/pom.xml site

## Cleanup:

mvn build-helper:remove-project-artifact

# Changed files:

  pdi-dataservice-client/src/main/java/org/pentaho/di/trans/dataservice/jdbc/ThinPreparedStatement.java
  pdi-dataservice-client/src/main/java/org/pentaho/di/trans/dataservice/jdbc/ThinStatement.java
  pdi-dataservice-client/src/test/java/org/pentaho/di/trans/dataservice/jdbc/MockDataInput.java
  pdi-dataservice-client/src/test/java/org/pentaho/di/trans/dataservice/jdbc/ThinPreparedStatementTest.java
  pdi-dataservice-client/src/test/java/org/pentaho/di/trans/dataservice/jdbc/ThinResultFactoryTest.java

# License header violations:
1. pdi-dataservice-client/src/test/java/org/pentaho/di/trans/dataservice/jdbc/ThinResultFactoryTest.java

# Unit test coverage change:

org.pentaho.di.trans.dataservice.jdbc.ThinPreparedStatement:
- instructionPercentCoverageChange : +0.31%
- branchPercentCoverageChange : +1.32%
- linePercentCoverageChange : +0.33%
- complexityPercentCoverageChange : +0.51%
- methodPercentCoverageChange : +0.17%

org.pentaho.di.trans.dataservice.jdbc.ThinStatement:
- instructionPercentCoverageChange : +0.14%
- linePercentCoverageChange : +0.13%

org.pentaho.di.trans.dataservice.jdbc.ThinResultSetMetaData:
- instructionPercentCoverageChange : +4.52%
- linePercentCoverageChange : +2.38%
- complexityPercentCoverageChange : +2.70%
- methodPercentCoverageChange : +4.55%

org.pentaho.di.trans.dataservice.jdbc.ThinResultFactory:
- instructionPercentCoverageChange : +18.52%
- linePercentCoverageChange : +21.43%

# Integration test coverage change:

org.pentaho.di.trans.dataservice.jdbc.ThinPreparedStatement:
- instructionPercentCoverageChange : +0.31%
- branchPercentCoverageChange : +1.32%
- linePercentCoverageChange : +0.33%
- complexityPercentCoverageChange : +0.51%
- methodPercentCoverageChange : +0.17%

org.pentaho.di.trans.dataservice.jdbc.ThinStatement:
- instructionPercentCoverageChange : +0.14%
- linePercentCoverageChange : +0.13%

org.pentaho.di.trans.dataservice.jdbc.ThinResultSetMetaData:
- instructionPercentCoverageChange : +4.52%
- linePercentCoverageChange : +2.38%
- complexityPercentCoverageChange : +2.70%
- methodPercentCoverageChange : +4.55%

org.pentaho.di.trans.dataservice.jdbc.ThinResultFactory:
- instructionPercentCoverageChange : +18.52%
- linePercentCoverageChange : +21.43%

**Pull request merged**
