### PR TITLE
[PDI-16683] - In Inspect Data, datasource published to the server wit…

### PR DESCRIPTION
**Pull request by YuryBY**
…h user having "<" character in password will not be shown in Analyzer.

@pamval, @smaring, could you please take a look?

### CODE REVIEW

**Comment by YuryBY** [comment]
@pamval, @smaring, @duarteteixeira, any updates?

**Comment by YuryBY** [comment]
@pamval, @smaring, @duarteteixeira, @DFieldFL, any updates?

**Review by DFieldFL — APPROVED** [review]

**Comment by DFieldFL** [comment]
I approve the changes. I will leave it up to others for merging.

**Comment by mchen-len-son** [comment]
@pamval can you please take a look?

**Pull request merged**
